### ISSUE TITLE
./configure: electrumdb.zip 404 Not Found

### ISSUE THREAD

**Issue by boyke** [vergecurrency/electrum-server#2]
./configure
Database not found in /home/electrum/db/.
Do you want to download it from the Verge Electrum repository to /home/electrum/db/ ? y
--2017-12-25 23:38:50--  https://github.com/vergecurrency/electrumdb/master/electrumdb.zip
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.

HTTP request sent, awaiting response... 404 Not Found
2017-12-25 23:38:51 ERROR 404: Not Found.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by justinvforvendetta** [comment]
ah you're going to want to say no to that until we push the electrum database to a repo. I'll get that up shortly

**Comment by boyke** [comment]
./configure 
Database not found in /home/electrum/db/.
Do you want to download it from the Verge Electrum repository to /home/electrum/db/ ? n
chown: cannot access ‘/home/electrum/db/’: No such file or directory

how to get server up (now) then? I want to help with server capacity.

**Comment by justinvforvendetta** [comment]
just say no, because when you start the server it will create a new databsse5

**Comment by philkunz** [comment]
Yeah, this doesn't work. No matter if you answer "n" or not. This is why I asked for a Docker image in the previous issue #1. Its probably some easy to overlook thing, yet people want it simple.

A few suggestions:
-> make the script not ask for options, but supply them as cli parameters by default (-> Docker compatibility)
-> Make the script user agnostic, don't expect a user called "electrum" on the system. (again: Docker compatibility)
-> Make a default Docker image (-> one command to install a server on already purchased latent resources where docker is available)

**Comment by philkunz** [comment]
ok, diving a little deeper in here, to get this done myself.

**Comment by justinvforvendetta** [comment]
this would be a nice addition since I don't think anyone's made a self deploying electrum server set up. I am glad community members are making new servers though

**Comment by philkunz** [comment]
@justinvforvendetta For the docker image, what do you prefer?
Pull Request for the Dockerfile (I might have to do some changes to how the config works though) or a fork that I maintain, with continuous upstream pulls?

**Comment by justinvforvendetta** [comment]
either way, wont argue lol
