### ISSUE TITLE
Verge Electrum wallet electrum-xvg not connecting. 

### ISSUE THREAD

**Issue by a4adky** [vergecurrency/electrum-server#6]
Hi Team,

I am using Verge Electrum walled 2.4.1 version on widows platform.  I am unable connect Verge. I can see red don on Electrum wallet and status displayed as Not connected. Please provide steps to fix this issue. 

Thanks
Mallik

**Comment by marpme** [comment]
Please migrate to electrum-xvg-tor since the clearnet version will be deprecated soonish. Thank you for your understandings :)
