### ISSUE TITLE
Cannot get my coins off electrum wallet

### ISSUE THREAD

**Issue by smoovevizion** [vergecurrency/electrum-server#7]
It has been a few years since I have checked this wallet but I cannot connect to move the coins or restore the wallet. How can I solve this problem?

**Comment by justinvforvendetta** [comment]
please migrate to the tor version, the clearnet version has not been supported since 2017. you can use your restore words to import the old one.

**Comment by smoovevizion** [comment]
that wallet doesn't connect to the internet

**Comment by smoovevizion** [comment]
never mind finally figured it out thanks for the direction
